name: Pylint

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install requests
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --disable=too-many-instance-attributes,too-few-public-methods,unused-argument,unused-import,too-many-return-statements,too-many-locals $(git ls-files '*.py')
